### ISSUE TITLE
Bootstrap generates scripts with deprecated changeEditorInterface method

### ISSUE THREAD

**Issue by canrozanes** [deluan/contentful-migrate#143]
When I run `npx ctf-migrate bootstrap -c contentType -s spaceID -e environmentID`, the package generates a script that uses the method `changeEditorInterface`. When I run this script, it emits the following warning:
`(deprecated) Method changeEditorInterface is deprecated and will be removed, use changeFieldControl instead`

**Comment by deluan** [comment]
Hey @canrozanes, what version are you using? This was fixed in https://github.com/deluan/contentful-migrate/pull/85 and was released already

**Comment by canrozanes** [comment]
I was indeed using a previous version. I was on v0.11.3. Upon updating to latest, the issue disappeared. As such, I'm closing this issue.
