### ISSUE TITLE
Could we update the contentful-migration dependency?

### ISSUE THREAD

**Issue by OriginalEXE** [deluan/contentful-migrate#183]
Hello,

The `contentful-migration` dependency is an old version and it's causing some vulnerability alerts because of the old axios version that it depends on.

Is there a reason that this library needs to stay on the 1.x version, or do you think it's realistic to update to the latest version? I can help with a PR, but just wanted to check if there's a reason why 1.x was kept while other dependencies were bumped.

Thanks

**Comment by deluan** [comment]
The only reason the `contentful-migration` lib is pinned is to ensure compatibility. Looks like the integration tests are not passing with the latest version. I'll try to fix this this week, but in the meantime feel free to try and send a PR, if you get the tests to pass

**Comment by OriginalEXE** [comment]
@deluan PR is ready, apologies for the delay: https://github.com/deluan/contentful-migrate/pull/196

**Comment by deluan** [comment]
Awesome! Thanks! Will take a look tonight.

**Comment by deluan** [comment]
Merged! Integration tests are passing now, and I will release a new version tonight. Thanks!
