### ISSUE TITLE
Support newer version of `contentful-migration` 

### ISSUE THREAD

**Issue by elskwid** [deluan/contentful-migrate#28]
Hi there @deluan,

We've been using and loving this tool to help organize and run our Contentful migrations. I attempted to update `content-migration` today to `0.16.6.` (I need a new feature they've released) and discovered that the dependency is set to: `^0.15.3`. 

What are the chances `contentful-migrate` can be updated to support the newer version? Is there anything I can do to help?

Thanks for the great project!

**Comment by elskwid** [comment]
@deluan I was able to [fork the repo](https://github.com/mutations/contentful-migrate/tree/dm/feature--bump-contentful-migration-version), update the dependency and run the full test suite successfully. Would a PR be helpful?

**Comment by deluan** [comment]
Yes, please. I didn't have time to look into this, but send me the PR and I'll release a new version

**Comment by deluan** [comment]
Done. New release: 0.9.7
