### ISSUE TITLE
Bootstrap issue

### ISSUE THREAD

**Issue by jmparsons** [deluan/contentful-migrate#56]
With the new ESLint CLIEngine update - if I have any rules in my eslintrc, the output is undefined. I have to have an empty `module.exports = {}` in order to produce results.

**Comment by deluan** [comment]
Currently `ctf-migrate` tries to use the rules defined in the project's `.eslintrc` file, if present. This has causing a lot of small issues (like this one). I'll disable this and only use `eslint-config-standard`. After the migration script is generated, devs can format it with their preferred tool before checkin the code.
