### ISSUE TITLE
Update bootstrap to use changeFieldControl

### ISSUE THREAD

**Issue by jmparsons** [deluan/contentful-migrate#81]
The bootstrap is using the deprecated version `changeEditorInterface`, new version is called `changeFieldControl` and takes 3 parameters.

https://github.com/contentful/contentful-migration/blob/master/README.md#changefieldcontrol-fieldid-widgetnamespace-widgetid-settings--void

```js
field.changeEditorInterface('colors', 'radio')

// widgetNamespace : string - "builtin" | "extension"

field.changeFieldControl('colors', 'builtin', 'radio')
```

**Comment by deluan** [comment]
Thanks for the report. I'll take a look at this today
